apiVersion: v1
kind: Service
metadata:
  name: {{ include "travel-time.fullname" . }}
  labels:
    {{- include "travel-time.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "travel-time.selectorLabels" . | nindent 4 }}
  ports:
    - name: rest
      port: {{ .Values.service.restPort }}
      targetPort: rest
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.restNodePort }}
      {{- end }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
